name: GitHub Actions Demo
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on: [push]
jobs:
  init:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        name: install node.js
        with:
          node-version: 22.17.0
      - name: install modules
        run: npm install
      - name: build project
        run: npm run build
      - name: ESLint
        run: npm run lint
      
